const ActionConstants = {
    FETCH_USERS_START : "FETCH_USERS_START",
    FETCH_USERS_SUCCESS :"FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE : "FETCH_USERS_FAILURE",

    CLEAR_USER_MESSAGES : "CLEAR_USER_MESSAGES"
}

export default ActionConstants