const ActionConstants = {
    FETCH_USERS_START : "FETCH_USERS_START",
    FETCH_USERS_SUCCESS :"FETCH_USERS_SUCCESS",
    FETCH_USERS_FAILURE : "FETCH_USERS_FAILURE",

    POST_TITLE_START:'POST_TITLE_START',
    POST_TITLE_SUCCESS:'POST_TITLE_SUCCESS',
    POST_TITLE_FAILURE:'POST_TITLE_FAILURE',

    UPDATE_TITLE_START:'UPDATE_TITLE_START',
    UPDATE_TITLE_SUCCESS:'UPDATE_TITLE_SUCCESS',
    UPDATE_TITLE_FAILURE:'UPDATE_TITLE_FAILURE',

    DELETE_TITLE_START:'DELETE_TITLE_START',
    DELETE_TITLE_SUCCESS:'DELETE_TITLE_SUCCESS',
    DELETE_TITLE_FAILURE:'DELETE_TITLE_FAILURE',

    CLEAR_USER_MESSAGES : "CLEAR_USER_MESSAGES"
}

export default ActionConstants